services:
  todo-api:
    container_name: todo-api
    image: todo-api
    build:
      context: ./apps/server
      dockerfile: ./Dockerfile.dev
    env_file:
      - ./apps/server/.env.dev
    ports:
      - 3001:3001
    depends_on:
      - redis
      - postgres
    develop:
      watch:
        - path: ./docker-compose.yml
          action: rebuild
        - path: ./apps/server/Dockerfile.dev
          action: rebuild
        - path: ./apps/server/package.json
          action: rebuild
        - path: ./apps/server/src
          target: /app/src
          action: sync

  client:
    container_name: todo-client
    image: todo-client
    build:
      context: ./apps/client
      dockerfile: ./Dockerfile.dev
    env_file:
      - ./apps/client/.env.dev
    ports:
      - 3000:3000
    develop:
      watch:
        - path: ./docker-compose.yml
          action: rebuild
        - path: ./apps/client/Dockerfile.dev
          action: rebuild
        - path: ./apps/client/package.json
          action: rebuild
        - path: ./apps/client/src
          target: /app/src
          action: sync

  postgres:
    container_name: todo-db
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=example
    ports:
      - 5432:5432

  redis:
    container_name: todo-redis
    image: redis:7
    environment:
      - REDIS_PASSWORD=password

  redis_commander:
    container_name: todo-redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
    depends_on:
      - redis

  openapi_generator:
    container_name: todo_openapi_generator
    image: openapitools/openapi-generator-cli
    depends_on:
      - todo-api
    volumes:
      - ./.generated/openapi:/local
    command: generate -i http://todo-api:3001/docs-json --generator-name typescript-axios -o /local/build --additional-properties=useSingleRequestParameter=true
