services:
  api:
    container_name: todo-api
    image: todo-api
    build:
      context: ./apps/server
      dockerfile: ./Dockerfile.dev
    env_file:
      - ./apps/server/.env.dev
    ports:
      - 3001:80
    depends_on:
      - redis
      - db
    healthcheck:
      test: curl -f http://api/health || exit 1
    develop:
      watch:
        - path: ./docker-compose.yml
          action: rebuild
        - path: ./apps/server/Dockerfile.dev
          action: rebuild
        - path: ./apps/server/package.json
          action: rebuild
        - path: ./apps/server/src
          target: /app/src
          action: sync

  client:
    container_name: todo-client
    image: todo-client
    build:
      context: ./apps/client
      dockerfile: ./Dockerfile.dev
    env_file:
      - ./apps/client/.env.dev
    ports:
      - 3000:3000
    depends_on:
      - api_generator
    develop:
      watch:
        - path: ./docker-compose.yml
          action: rebuild
        - path: ./apps/client/Dockerfile.dev
          action: rebuild
        - path: ./apps/client/package.json
          action: rebuild
        - path: ./apps/client/src
          target: /app/src
          action: sync

  db:
    container_name: todo-db
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=example
    ports:
      - 5432:5432

  redis:
    container_name: todo-redis
    image: redis:7
    environment:
      - REDIS_PASSWORD=password

  redis_commander:
    container_name: todo-redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
    depends_on:
      - redis

  api_generator:
    container_name: todo-api-generator
    image: openapitools/openapi-generator-cli
    depends_on:
      api: 
        condition: service_healthy
        restart: true
    volumes:
      - ./apps/client/src/api/generated:/local/build
    command: generate -i http://api/docs-json -g typescript-axios -o /local/build -p=useSingleRequestParameter=true
