# syntax=docker/dockerfile:1

FROM node:22-slim
RUN apt update && apt install -y procps

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml? ./
RUN pnpm i
RUN pnpm fetch

COPY . .
ENTRYPOINT [ "pnpm", "run", "start:dev" ]